### ISSUE TITLE
humanoid robot controll

### ISSUE THREAD

**Issue by netpipe** [markniu/PandaZHU#3]
i wonder if more stepper drivers can be added for a robot control board for humanoid robot. need like 20

https://www.thingiverse.com/thing:4908016

**Comment by markniu** [comment]
the robot is cool! it's possible to add more than 20 stepper drivers,but need to add one more expand gpio chip or just an external board with expand gpio chip.

**Comment by netpipe** [comment]
pcf8574 i2c expander ?
