### ISSUE TITLE
Newer Marlin Firmware

### ISSUE THREAD

**Issue by Dschorim** [markniu/PandaZHU#9]
What is the Marlin folder for? isn't support for the PandaZHU already merged into the official Marlin firmware?

**Comment by markniu** [comment]
the Marlin folder in this github is just for test or new features which have not merged into offical Marlin,E.g. PandaCAN,PandaBed.

The official Marlin has merged this board: https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.1.x/Marlin/src/pins/esp32
